spring:
  profiles:
    active: jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/itemsdb
    username: app
    password: app

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
